/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package felulet;

import alaposztalyok.Global;
import java.awt.Graphics;
import vezerlo.Vezerlo;

/**
 *
 * @author kunec
 */
public class JatekPanel extends javax.swing.JPanel {

    /**
     *
     */
    private static final long serialVersionUID = 1L;
    private Vezerlo vezerlo;

    public JatekPanel() {
        initComponents();
        this.setSize(Global.JATEK_FELULET_SZELESSEG, Global.JATEK_FELULET_MAGASSAG);
        this.setVisible(false);
        gazPedal1.addMouseListener(gazPedal1);
        gazPedal1.setLocation(710, 380);
        fokozatLabel1.setLocation(560, 450);
        fokozatLabel2.setLocation(200, 450);
        valto1.addMouseListener(valto1);
        valto1.setLocation(560, 390);
        //nitroGomb1.addMouseListener(nitroGomb1);
       // nitroGomb1.setLocation(710, 300);
    }

    public void setVezerlo(Vezerlo vezerlo) {
        this.vezerlo = vezerlo;
    }

    @Override
    protected void paintComponent(Graphics g) {
        if (vezerlo != null) {
            vezerlo.rajzol(g);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gazPedal1 = new gombok.GazPedal();
        fokozatLabel1 = new label.FokozatLabel();
        valto1 = new gombok.Valto();
        fokozatLabel2 = new label.FokozatLabel();

        setBackground(new java.awt.Color(51, 51, 51));
        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        gazPedal1.setText("gazPedal1");
        gazPedal1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                gazPedal1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                gazPedal1MouseReleased(evt);
            }
        });

        fokozatLabel1.setText("sebessegLabel1");

        valto1.setText("valto1");
        valto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valto1ActionPerformed(evt);
            }
        });

        fokozatLabel2.setText("fokozatLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(fokozatLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(fokozatLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                .addComponent(valto1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(gazPedal1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(180, Short.MAX_VALUE)
                .addComponent(fokozatLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 175, Short.MAX_VALUE)
                .addComponent(fokozatLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gazPedal1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valto1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void gazPedal1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gazPedal1MousePressed
        vezerlo.mousePressed(evt);
    }//GEN-LAST:event_gazPedal1MousePressed

    private void valto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valto1ActionPerformed
        vezerlo.valtas();
    }//GEN-LAST:event_valto1ActionPerformed

    private void gazPedal1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gazPedal1MouseReleased
        vezerlo.mouseReleased(evt);
    }//GEN-LAST:event_gazPedal1MouseReleased

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
        fokozatLabel1.setText("" + 1);
        fokozatLabel2.setText("0");
    }//GEN-LAST:event_formAncestorAdded


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private label.FokozatLabel fokozatLabel1;
    private label.FokozatLabel fokozatLabel2;
    private gombok.GazPedal gazPedal1;
    private gombok.Valto valto1;
    // End of variables declaration//GEN-END:variables
/**
     * kiírja az aktuális fokozat számát
     *
     * @param autoActualFokozat
     */
    public void aktualisFokozatotKiir(int autoActualFokozat) {
        fokozatLabel1.setText("" + (autoActualFokozat));
    }

    /**
     * kiírja a sebességet
     *
     * @param utDX
     */
    public void sebessegetKiir(double utDX) {
        fokozatLabel2.setText(String.format("%3.0f", utDX));
    }
}
