/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package felulet;

import alaposztalyok.Global;
import vezerlo.Vezerlo;

/**
 *
 * @author kunec
 */
public class JatekFrame extends javax.swing.JFrame {

    /**
     *
     */
    private static final long serialVersionUID = 664695234511609434L;

    /**
     * Creates new form NewJFrame
     */
    public JatekFrame() {
        initComponents();
        this.setSize(Global.JATEK_FELULET_SZELESSEG, Global.JATEK_FELULET_MAGASSAG + 20);
        this.setTitle(Global.CIM);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        beallit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bejelentkezoPanel1 = new felulet.BejelentkezoPanel();
        adatPanel2 = new felulet.AdatPanel();
        boltPanel2 = new felulet.BoltPanel();
        jatekPanel2 = new felulet.JatekPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().add(bejelentkezoPanel1, java.awt.BorderLayout.CENTER);
        getContentPane().add(adatPanel2, java.awt.BorderLayout.PAGE_END);
        getContentPane().add(boltPanel2, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout jatekPanel2Layout = new javax.swing.GroupLayout(jatekPanel2);
        jatekPanel2.setLayout(jatekPanel2Layout);
        jatekPanel2Layout.setHorizontalGroup(
            jatekPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jatekPanel2Layout.setVerticalGroup(
            jatekPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        getContentPane().add(jatekPanel2, java.awt.BorderLayout.LINE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new NewJFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private felulet.AdatPanel adatPanel2;
    private felulet.BejelentkezoPanel bejelentkezoPanel1;
    private felulet.BoltPanel boltPanel2;
    private felulet.JatekPanel jatekPanel2;
    // End of variables declaration//GEN-END:variables
/**
     * beállítja a vezérlőt és a paneleket
     */
    private void beallit() {
        Vezerlo vezerlo = new Vezerlo(bejelentkezoPanel1, adatPanel2, boltPanel2, jatekPanel2);
        bejelentkezoPanel1.setVezerlo(vezerlo);
        adatPanel2.setVezerlo(vezerlo);
        boltPanel2.setVezerlo(vezerlo);
        jatekPanel2.setVezerlo(vezerlo);

    }
}
