/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package felulet;

import alaposztalyok.Global;
import vezerlo.Vezerlo;

/**
 *
 * @author kunec
 */
public class KezdoFrame extends javax.swing.JFrame {

    /**
     *
     */
    private static final long serialVersionUID = 5624679973199105213L;

    /**
     * Creates new form KezdoFrame
     */
    public KezdoFrame() {
        initComponents();
        this.setSize(Global.KEZDO_FELULET_SZELESSEG, Global.KEZDO_FELULET_MAGASSAG);
        this.setTitle(Global.CIM);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kezdoPanel1 = new felulet.KezdoPanel();
        sugoPanel1 = new felulet.SugoPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().add(kezdoPanel1, java.awt.BorderLayout.CENTER);
        getContentPane().add(sugoPanel1, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KezdoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KezdoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KezdoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KezdoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KezdoFrame().indit();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private felulet.KezdoPanel kezdoPanel1;
    private felulet.SugoPanel sugoPanel1;
    // End of variables declaration//GEN-END:variables

    private void indit() {
        this.setVisible(true);
        Vezerlo vezerlo = new Vezerlo(kezdoPanel1, sugoPanel1);
        kezdoPanel1.setVezerlo(vezerlo);
        sugoPanel1.setVezerlo(vezerlo);
    }
}
