/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package felulet;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import vezerlo.Vezerlo;

/**
 *
 * @author kunec
 */
public class KezdoPanel extends javax.swing.JPanel {

    /**
     *
     */
    private static final long serialVersionUID = -3893072275341420291L;
    private Vezerlo vezerlo;
    private Image kep = new ImageIcon(this.getClass().getResource("/kepek/drag2.jpg")).getImage();

    public KezdoPanel() {
        initComponents();
        exitGomb1.addActionListener(exitGomb1);
        playGomb1.addActionListener(playGomb1);
        exitGomb1.addMouseListener(exitGomb1);
        playGomb1.addMouseListener(playGomb1);
        sugoGomb1.addMouseListener(sugoGomb1);
    }

    public void setVezerlo(Vezerlo vezerlo) {
        this.vezerlo = vezerlo;
    }

    /**
     * kirajzolja a hátteret a panelen
     *
     * @param g
     */
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        g.drawImage(kep, 0, 0, this.getWidth(), this.getHeight(), this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exitGomb1 = new gombok.ExitGomb();
        playGomb1 = new gombok.InditGomb();
        sugoGomb1 = new gombok.SugoGomb();

        setBackground(new java.awt.Color(102, 102, 255));

        sugoGomb1.setText("sugoGomb1");
        sugoGomb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sugoGomb1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(304, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(playGomb1, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                    .addComponent(exitGomb1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sugoGomb1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(141, Short.MAX_VALUE)
                .addComponent(playGomb1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sugoGomb1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exitGomb1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sugoGomb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sugoGomb1ActionPerformed
        vezerlo.sugoPanel();
    }//GEN-LAST:event_sugoGomb1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private gombok.ExitGomb exitGomb1;
    private gombok.InditGomb playGomb1;
    private gombok.SugoGomb sugoGomb1;
    // End of variables declaration//GEN-END:variables
}
